export const ADD_DUNGEON = 'ADD_DUNGEON';
export const ADD_ROOM_TO_DUNGEON = 'ADD_ROOM_TO_DUNGEON';
export const ADD_CORRIDORS_TO_DUNGEON = "ADD_CORRIDORS_TO_DUNGEON";
export const PUT_PLAYER = "PUT_PLAYER";
export const PUT_BOSS = "PUT_BOSS";
export const ATTACK_ENEMY = "ATTACK_ENEMY";
export const PUT_STAFF = "PUT_STAFF";
